version: '3'

services:
  movie_app_node_js:
    build:
      context: ./../../
      dockerfile: etc/docker/Dockerfile
    volumes:
      - ./../../:/var/app
    ports:
      - "9333:9333"
    environment:
      - APP_ENV=dev