module.exports =
[
  {
    "Title": "Avatar",
    "Plot": "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
    "Runtime": "162 min",
    "Released": "18 Dec 2009",
  },
  {
    "Title": "I Am Legend",
    "Plot": "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
    "Genre": "Drama, Horror, Sci-Fi",
    "Actors": "Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield",
    "Runtime": "101 min",
    "Released": "14 Dec 2007",
  },
  {
    "Title": "300",
    "Plot": "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
    "Genre": "Action, Drama, Fantasy",
    "Actors": "Gerard Butler, Lena Headey, Dominic West, David Wenham",
    "Runtime": "117 min",
    "Released": "09 Mar 2007",
  },
  {
    "Title": "The Avengers",
    "Plot": "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    "Genre": "Action, Sci-Fi, Thriller",
    "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "Runtime": "143 min",
    "Released": "04 May 2012",
  },
  {
    "Title": "The Wolf of Wall Street",
    "Plot": "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    "Genre": "Biography, Comedy, Crime",
    "Actors": "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
    "Runtime": "180 min",
    "Released": "25 Dec 2013",
  },
  {
    "Title": "Interstellar",
    "Plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "Genre": "Adventure, Drama, Sci-Fi",
    "Actors": "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
    "Runtime": "169 min",
    "Released": "07 Nov 2014",
  },
  {
    "Title": "Game of Thrones",
    "Plot": "While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.",
    "Genre": "Adventure, Drama, Fantasy",
    "Actors": "Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
    "Runtime": "56 min",
    "Released": "17 Apr 2011",
  },
  {
    "Title": "Narcos",
    "Plot": "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
    "Genre": "Biography, Crime, Drama",
    "Actors": "Wagner Moura, Boyd Holbrook, Pedro Pascal, Joanna Christie",
    "Runtime": "49 min",
    "Released": "28 Aug 2015",
  },
  {
    "Title": "Breaking Bad",
    "Plot": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's financial future.",
    "Genre": "Crime, Drama, Thriller",
    "Actors": "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
    "Runtime": "49 min",
    "Released": "20 Jan 2008",
  },
  {
    "Title": "Doctor Strange",
    "Plot": "After his career is destroyed, a brilliant but arrogant and conceited surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Rachel McAdams, Benedict Cumberbatch, Mads Mikkelsen, Tilda Swinton",
    "Runtime": "N/A",
    "Released": "04 Nov 2016",
  },
  {
    "Title": "Rogue One: A Star Wars Story",
    "Plot": "The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.",
    "Genre": "Action, Adventure, Sci-Fi",
    "Actors": "Felicity Jones, Riz Ahmed, Mads Mikkelsen, Ben Mendelsohn",
    "Runtime": "N/A",
    "Released": "16 Dec 2016",
  },
  {
    "Title": "Assassin's Creed",
    "Plot": "When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.",
    "Genre": "Action, Adventure, Fantasy",
    "Actors": "Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons",
    "Runtime": "N/A",
    "Released": "21 Dec 2016",
  },
];